# Funding links for the project. Add or remove platforms as needed.
# Common providers: patreon, open_collective, github

github: [2MuchC0ff33]
# open_collective: 'your-collective'
# patreon: 'your-patreon'
